### PR TITLE
Add return type to home indicator component

### PR DESCRIPTION
**Pull request by isilher**
Thank you for making this library and for adding TypeScript to it! When updating to v0.2.9 I found that although the properties are now properly typed, my TS configuration still gave me a warning:

> error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

By only typing the props, the HomeIndicator component was missing a clear return type. This proposed change instead types the functional component, setting the return type to be a React Functional Component that will accept the properties defined in Props.

Cheers!

### CODE REVIEW

File: index.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ const isIos = Platform.OS === "ios";
 
 type Props = { autoHidden: boolean };
 
-export const HomeIndicator = (props: Props) => {
+export const HomeIndicator: React.FC<Props> = (props) => {
```
Comment (michaelknoch) [inline index.tsx:9]: the problem with React.FC is that it implicitly adds children to the props. 
`export const HomeIndicator = (props: Props): ReactElement | null => {` could work, but this is a bit unusual

Comment (isilher) [reply index.tsx:9]: That is a good point and a reason to move away from using `React.FC` in general. Your alternative seems reasonable to me, and for TypeScript support helps us more than `any`, why would it be unusual in your opinion?
